package model;
// Generated Apr 16, 2018 10:03:05 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cashier generated by hbm2java
 */
public class Cashier  implements java.io.Serializable {


     private int userId;
     private User user;
     private String address;
     private Date hireDate;
     private Integer status;

    public Cashier() {
    }

	
    public Cashier(User user) {
        this.user = user;
    }
    public Cashier(User user, String address, Date hireDate, Integer status) {
       this.user = user;
       this.address = address;
       this.hireDate = hireDate;
       this.status = status;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


