package model;
// Generated Apr 16, 2018 10:03:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cinema generated by hbm2java
 */
public class Cinema  implements java.io.Serializable {


     private String cinemaName;
     private String address;
     private String city;
     private String province;
     private Set<Studio> studios = new HashSet<Studio>(0);

    public Cinema() {
    }

	
    public Cinema(String cinemaName) {
        this.cinemaName = cinemaName;
    }
    public Cinema(String cinemaName, String address, String city, String province, Set<Studio> studios) {
       this.cinemaName = cinemaName;
       this.address = address;
       this.city = city;
       this.province = province;
       this.studios = studios;
    }
    
    public Cinema(String cinemaName, String address, String city, String province) {
       this.cinemaName = cinemaName;
       this.address = address;
       this.city = city;
       this.province = province;
    }
   
    public String getCinemaName() {
        return this.cinemaName;
    }
    
    public void setCinemaName(String cinemaName) {
        this.cinemaName = cinemaName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public Set<Studio> getStudios() {
        return this.studios;
    }
    
    public void setStudios(Set<Studio> studios) {
        this.studios = studios;
    }




}


