package model;
// Generated Apr 16, 2018 10:03:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Schedule generated by hbm2java
 */
public class Schedule  implements java.io.Serializable {


     private ScheduleId id;
     private Movie movie;
     private Studio studio;
     private Integer price;
     private Set<Transaction> transactions = new HashSet<Transaction>(0);

    public Schedule() {
    }

	
    public Schedule(ScheduleId id, Studio studio) {
        this.id = id;
        this.studio = studio;
    }
    public Schedule(ScheduleId id, Movie movie, Studio studio, Integer price, Set<Transaction> transactions) {
       this.id = id;
       this.movie = movie;
       this.studio = studio;
       this.price = price;
       this.transactions = transactions;
    }
   
    public ScheduleId getId() {
        return this.id;
    }
    
    public void setId(ScheduleId id) {
        this.id = id;
    }
    public Movie getMovie() {
        return this.movie;
    }
    
    public void setMovie(Movie movie) {
        this.movie = movie;
    }
    public Studio getStudio() {
        return this.studio;
    }
    
    public void setStudio(Studio studio) {
        this.studio = studio;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }




}


