package model;
// Generated Apr 16, 2018 10:03:05 PM by Hibernate Tools 4.3.1



/**
 * Seat generated by hbm2java
 */
public class Seat  implements java.io.Serializable {


     private SeatId id;
     private Studio studio;

    public Seat() {
    }

    public Seat(SeatId id, Studio studio) {
       this.id = id;
       this.studio = studio;
    }
   
    public SeatId getId() {
        return this.id;
    }
    
    public void setId(SeatId id) {
        this.id = id;
    }
    public Studio getStudio() {
        return this.studio;
    }
    
    public void setStudio(Studio studio) {
        this.studio = studio;
    }




}


