package model;
// Generated Apr 16, 2018 10:03:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Studio generated by hbm2java
 */
public class Studio  implements java.io.Serializable {


     private Integer studioNumber;
     private Cinema cinema;
     private String studioName;
     private Integer rowCapacity;
     private Integer colCapacity;
     private Set<Schedule> schedules = new HashSet<Schedule>(0);
     private Set<Seat> seats = new HashSet<Seat>(0);

    public Studio() {
    }

    public Studio(Cinema cinema, String studioName, Integer rowCapacity, Integer colCapacity, Set<Schedule> schedules, Set<Seat> seats) {
       this.cinema = cinema;
       this.studioName = studioName;
       this.rowCapacity = rowCapacity;
       this.colCapacity = colCapacity;
       this.schedules = schedules;
       this.seats = seats;
    }
   
    public Integer getStudioNumber() {
        return this.studioNumber;
    }
    
    public void setStudioNumber(Integer studioNumber) {
        this.studioNumber = studioNumber;
    }
    public Cinema getCinema() {
        return this.cinema;
    }
    
    public void setCinema(Cinema cinema) {
        this.cinema = cinema;
    }
    public String getStudioName() {
        return this.studioName;
    }
    
    public void setStudioName(String studioName) {
        this.studioName = studioName;
    }
    public Integer getRowCapacity() {
        return this.rowCapacity;
    }
    
    public void setRowCapacity(Integer rowCapacity) {
        this.rowCapacity = rowCapacity;
    }
    public Integer getColCapacity() {
        return this.colCapacity;
    }
    
    public void setColCapacity(Integer colCapacity) {
        this.colCapacity = colCapacity;
    }
    public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }
    public Set<Seat> getSeats() {
        return this.seats;
    }
    
    public void setSeats(Set<Seat> seats) {
        this.seats = seats;
    }




}


