package model;
// Generated Apr 16, 2018 10:03:05 PM by Hibernate Tools 4.3.1



/**
 * TicketId generated by hbm2java
 */
public class TicketId  implements java.io.Serializable {


     private int transactionId;
     private String seatPosition;

    public TicketId() {
    }

    public TicketId(int transactionId, String seatPosition) {
       this.transactionId = transactionId;
       this.seatPosition = seatPosition;
    }
   
    public int getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }
    public String getSeatPosition() {
        return this.seatPosition;
    }
    
    public void setSeatPosition(String seatPosition) {
        this.seatPosition = seatPosition;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TicketId) ) return false;
		 TicketId castOther = ( TicketId ) other; 
         
		 return (this.getTransactionId()==castOther.getTransactionId())
 && ( (this.getSeatPosition()==castOther.getSeatPosition()) || ( this.getSeatPosition()!=null && castOther.getSeatPosition()!=null && this.getSeatPosition().equals(castOther.getSeatPosition()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTransactionId();
         result = 37 * result + ( getSeatPosition() == null ? 0 : this.getSeatPosition().hashCode() );
         return result;
   }   


}


